#!/bin/bash

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR

if [ -d free/target ]; then
  cd free/target/universal/
  tar xvzf finch-todo-backend-free-0.1.0.tgz
  finch-todo-backend-free-0.1.0/bin/finch-todo-backend-free -admin.port=':0' -Dhttp.externalUrl='http://diy-ilyamurzinov.rhcloud.com' -Dhttp.host=$OPENSHIFT_DIY_IP -Dhttp.port=$OPENSHIFT_DIY_PORT > ${OPENSHIFT_LOG_DIR}server.log 2>&1 &
elif [ -d minimal/target ]; then
  cd minimal/target/universal/
  tar xvzf finch-todo-backend-minimal-0.1.0.tgz
  finch-todo-backend-minimal-0.1.0/bin/finch-todo-backend-minimal -admin.port=':0' -Dhttp.externalUrl='http://diy-ilyamurzinov.rhcloud.com' -Dhttp.host=$OPENSHIFT_DIY_IP -Dhttp.port=$OPENSHIFT_DIY_PORT > ${OPENSHIFT_LOG_DIR}server.log 2>&1 &
fi